# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install python requirements.txt
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Execute python tests
        run: |
          source env/bin/activate
          pytest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Subir script etl_dim_date.py al bucket de Glue
        run: |
          echo "Subiendo punto3.py a S3..."
          aws s3 cp punto3.py s3://aws-glue-assets-370929298138-us-east-1/scripts/punto3.py --region us-east-1 --acl bucket-owner-full-control
          echo "Script actualizado correctamente en Glue Assets"
